"""
Periodic job seeder — designed to run on a cron schedule.

Usage (manual run):
  docker compose exec backend python seed_new_jobs.py

Adds 10+ fresh jobs per category across all 10 industry verticals.
Safely skips any job whose (title, company_id) already exists.
"""
import asyncio
import re
import random
from datetime import datetime, timedelta

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy import select

from app.core.config import settings
from app.models.models import Company, Industry, Job, JobType

engine = create_async_engine(settings.DATABASE_URL, echo=False)
Session = async_sessionmaker(bind=engine, class_=AsyncSession, expire_on_commit=False)


def to_slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


# ── Job pool ─────────────────────────────────────────────────────────────────
# Each dict: title, company (must match DB or will be created), industry slug,
# location, remote, job_type, salary_min, salary_max, skills, is_featured,
# description, requirements, benefits.

JOBS_POOL = [

    # ── Technology (10 jobs) ─────────────────────────────────────────────────
    {
        "title": "Principal Software Architect",
        "company": "Acme Technologies", "industry": "technology",
        "location": "New York, NY", "remote": True,
        "job_type": JobType.full_time, "salary_min": 190000, "salary_max": 240000,
        "skills": ["System Design", "Microservices", "AWS", "Python", "Java"],
        "is_featured": True,
        "description": "Define and own the technical architecture for our next-generation platform.\n\nResponsibilities\n\n• Lead architectural decisions across 15 engineering squads\n• Define APIs, data models, and cross-service contracts\n• Mentor senior engineers and grow technical leadership bench",
        "requirements": "12+ years software engineering, 4+ years architect-level experience, proven track record designing systems at scale.",
        "benefits": "Top-of-market compensation, significant equity, executive visibility, annual architecture summit attendance.",
    },
    {
        "title": "Distributed Systems Engineer",
        "company": "DataFlow Inc.", "industry": "technology",
        "location": "San Francisco, CA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 155000, "salary_max": 200000,
        "skills": ["Go", "Kafka", "Kubernetes", "Distributed Systems", "gRPC"],
        "is_featured": False,
        "description": "Build the distributed compute layer that powers DataFlow's real-time analytics at petabyte scale.\n\nResponsibilities\n\n• Design fault-tolerant, high-throughput data processing systems\n• Own service reliability targets (99.99% SLA)\n• Collaborate with ML teams on low-latency feature serving",
        "requirements": "5+ years distributed systems engineering, Go or Rust required, Kafka/Flink expertise.",
        "benefits": "Equity, remote-first, dedicated research time allocation.",
    },
    {
        "title": "Staff Data Scientist – Growth",
        "company": "DataFlow Inc.", "industry": "technology",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 160000, "salary_max": 210000,
        "skills": ["Python", "Causal Inference", "A/B Testing", "SQL", "Statistics"],
        "is_featured": True,
        "description": "Drive data-driven growth decisions across our $50M ARR business using rigorous causal inference methods.\n\nResponsibilities\n\n• Design and analyse A/B experiments across the funnel\n• Build models predicting churn, LTV, and conversion\n• Partner with growth PMs to prioritise highest-impact experiments",
        "requirements": "6+ years data science, strong causal inference background, PhD in Statistics preferred.",
        "benefits": "Remote-first, top compensation, quarterly data science symposium.",
    },
    {
        "title": "Infrastructure Engineer – GPU Clusters",
        "company": "Horizon AI", "industry": "technology",
        "location": "San Francisco, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 160000, "salary_max": 220000,
        "skills": ["CUDA", "Kubernetes", "Networking", "Linux", "Python"],
        "is_featured": False,
        "description": "Build and operate the GPU infrastructure that trains our frontier AI models.\n\nYou'll own the hardware and software stack that enables training runs on thousands of GPUs.",
        "requirements": "4+ years infrastructure engineering, hands-on GPU cluster experience, deep Linux and networking knowledge.",
        "benefits": "Top compensation, equity, direct impact on AI research.",
    },
    {
        "title": "API Integration Engineer",
        "company": "CloudNative Corp", "industry": "technology",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 105000, "salary_max": 140000,
        "skills": ["REST APIs", "GraphQL", "Python", "Node.js", "Webhooks"],
        "is_featured": False,
        "description": "Build the integrations layer that connects CloudNative's platform to 200+ enterprise systems and third-party APIs.",
        "requirements": "3+ years API integration engineering, REST and GraphQL expertise, familiarity with OAuth/OIDC.",
        "benefits": "Remote, flexible hours, technical growth path.",
    },
    {
        "title": "Database Reliability Engineer",
        "company": "Acme Technologies", "industry": "technology",
        "location": "New York, NY", "remote": True,
        "job_type": JobType.full_time, "salary_min": 135000, "salary_max": 175000,
        "skills": ["PostgreSQL", "MySQL", "Performance Tuning", "Replication", "AWS RDS"],
        "is_featured": False,
        "description": "Own reliability, performance, and scalability of our database fleet serving 50M+ users across 12 PostgreSQL clusters.",
        "requirements": "4+ years DBA or DBE experience, PostgreSQL expertise required, high-availability setup experience.",
        "benefits": "Strong comp, remote option, on-call bonus structure.",
    },
    {
        "title": "React Native Mobile Engineer",
        "company": "DataFlow Inc.", "industry": "technology",
        "location": "San Francisco, CA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 120000, "salary_max": 160000,
        "skills": ["React Native", "TypeScript", "iOS", "Android", "GraphQL"],
        "is_featured": False,
        "description": "Build our cross-platform mobile analytics app, bringing DataFlow's insights to mobile-first enterprise users.",
        "requirements": "3+ years React Native, shipped production app required, TypeScript expertise.",
        "benefits": "Remote, equity, $3K home office stipend.",
    },
    {
        "title": "Observability Engineer",
        "company": "CloudNative Corp", "industry": "technology",
        "location": "Seattle, WA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 125000, "salary_max": 165000,
        "skills": ["OpenTelemetry", "Prometheus", "Grafana", "Distributed Tracing", "Python"],
        "is_featured": False,
        "description": "Build the observability platform that gives engineers deep visibility into our distributed cloud infrastructure.",
        "requirements": "3+ years observability or SRE, OpenTelemetry experience, strong metrics/tracing background.",
        "benefits": "Remote-first, on-call bonuses, engineering autonomy.",
    },
    {
        "title": "AI Product Manager",
        "company": "Horizon AI", "industry": "technology",
        "location": "San Francisco, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 160000, "salary_max": 210000,
        "skills": ["AI Products", "Product Strategy", "LLMs", "User Research", "Roadmapping"],
        "is_featured": True,
        "description": "Define and ship AI products that millions of users depend on for coding, writing, and reasoning.\n\nYou'll work at the frontier — experimenting with capabilities before they're announced.",
        "requirements": "5+ years PM experience, strong AI/ML intuition, track record of shipping 0-to-1 products.",
        "benefits": "Equity, on-site at SF HQ, access to frontier model capabilities.",
    },
    {
        "title": "Platform Product Manager",
        "company": "CloudNative Corp", "industry": "technology",
        "location": "Seattle, WA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 140000, "salary_max": 180000,
        "skills": ["Product Management", "Developer Experience", "APIs", "Cloud", "Agile"],
        "is_featured": False,
        "description": "Own the developer platform product strategy — the internal tools and APIs that 500+ engineers rely on daily.",
        "requirements": "4+ years PM experience, prior engineering background strongly preferred, API or developer tools experience.",
        "benefits": "Stock options, flexible hybrid schedule, $5K annual learning budget.",
    },

    # ── Healthcare (10 jobs) ─────────────────────────────────────────────────
    {
        "title": "Genetic Counselor",
        "company": "NovaBio Labs", "industry": "healthcare",
        "location": "Boston, MA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 105000,
        "skills": ["Genetic Counseling", "Variant Interpretation", "Patient Education", "EMR", "Oncology Genetics"],
        "is_featured": False,
        "description": "Provide genetic counseling support for patients enrolled in our oncology clinical trials.\n\nResponsibilities\n\n• Interpret germline and somatic variant reports\n• Counsel patients on hereditary cancer risk\n• Collaborate with PIs on protocol development",
        "requirements": "CGC board certification, Master's in Genetic Counseling, 2+ years clinical or research counseling.",
        "benefits": "Remote-friendly, mission-driven, publication opportunities.",
    },
    {
        "title": "Health Informatics Specialist",
        "company": "MetroHealth System", "industry": "healthcare",
        "location": "Cleveland, OH", "remote": True,
        "job_type": JobType.full_time, "salary_min": 72000, "salary_max": 98000,
        "skills": ["Epic", "HL7 FHIR", "SQL", "Clinical Data", "Interoperability"],
        "is_featured": False,
        "description": "Improve clinical data quality and interoperability across our Epic EHR environment.\n\nYou'll build interfaces, map data standards, and support clinical analytics initiatives.",
        "requirements": "3+ years health informatics, Epic certification preferred, HL7 and FHIR expertise.",
        "benefits": "Hybrid schedule, tuition reimbursement, full benefits.",
    },
    {
        "title": "Care Manager – Remote",
        "company": "Peak Wellness Group", "industry": "healthcare",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 58000, "salary_max": 78000,
        "skills": ["Care Management", "Case Management", "Chronic Disease", "Motivational Interviewing", "EMR"],
        "is_featured": False,
        "description": "Support patients with chronic conditions through proactive care management via telehealth.\n\nYou'll coordinate care, close care gaps, and help members navigate a complex health system.",
        "requirements": "RN license or case management certification, 2+ years care management, telehealth experience preferred.",
        "benefits": "100% remote, mission-driven, flexible schedule.",
    },
    {
        "title": "Radiology AI Specialist",
        "company": "NovaBio Labs", "industry": "healthcare",
        "location": "Boston, MA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 110000, "salary_max": 145000,
        "skills": ["Medical Imaging", "Deep Learning", "Python", "DICOM", "Computer Vision"],
        "is_featured": False,
        "description": "Develop and validate AI models that assist radiologists in detecting and characterising tumours.\n\nYou'll work at the intersection of deep learning and clinical radiology.",
        "requirements": "MS/PhD in Biomedical Engineering or CS, 3+ years medical imaging AI, DICOM expertise.",
        "benefits": "Research environment, publications encouraged, remote option.",
    },
    {
        "title": "Medical Director – Primary Care",
        "company": "Peak Wellness Group", "industry": "healthcare",
        "location": "Miami, FL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 230000, "salary_max": 300000,
        "skills": ["Primary Care", "Clinical Leadership", "Quality Improvement", "Value-Based Care", "EMR"],
        "is_featured": True,
        "description": "Lead clinical strategy and quality for our network of 20 primary care centres across South Florida.",
        "requirements": "MD/DO, board-certified Family Medicine or Internal Medicine, 5+ years clinical leadership.",
        "benefits": "Executive comp, malpractice covered, sign-on bonus, full benefits.",
    },
    {
        "title": "Clinical Trials Regulatory Specialist",
        "company": "NovaBio Labs", "industry": "healthcare",
        "location": "Boston, MA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 85000, "salary_max": 115000,
        "skills": ["FDA Regulations", "IND", "ICH Guidelines", "eCTD", "Regulatory Affairs"],
        "is_featured": False,
        "description": "Prepare and manage regulatory submissions for our oncology pipeline (IND, IMPD, annual reports).",
        "requirements": "RAC certification preferred, 4+ years regulatory affairs in pharma or biotech, IND experience required.",
        "benefits": "Remote-friendly, equity in comp packages, mission-driven culture.",
    },
    {
        "title": "Occupational Health Nurse",
        "company": "MetroHealth System", "industry": "healthcare",
        "location": "Cleveland, OH", "remote": False,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 88000,
        "skills": ["Occupational Health", "OSHA", "Workers Compensation", "Health Surveillance", "Case Management"],
        "is_featured": False,
        "description": "Provide occupational health services for our 8,000-employee healthcare system, focusing on workplace injury prevention.",
        "requirements": "RN license, COHN or COHN-S certification preferred, 2+ years occupational health.",
        "benefits": "Hospital system benefits, no nights/weekends, professional development.",
    },
    {
        "title": "Behavioral Health Data Analyst",
        "company": "Peak Wellness Group", "industry": "healthcare",
        "location": "Miami, FL", "remote": True,
        "job_type": JobType.full_time, "salary_min": 68000, "salary_max": 90000,
        "skills": ["SQL", "Python", "Healthcare Analytics", "Behavioral Health", "Tableau"],
        "is_featured": False,
        "description": "Analyse clinical and claims data to measure outcomes and drive quality improvement in our behavioral health programmes.",
        "requirements": "2+ years healthcare analytics, SQL proficient, behavioral health domain knowledge preferred.",
        "benefits": "Remote, mission-driven work, career growth.",
    },
    {
        "title": "Pharmacy Director – Oncology",
        "company": "NovaBio Labs", "industry": "healthcare",
        "location": "Boston, MA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 140000, "salary_max": 185000,
        "skills": ["Oncology Pharmacy", "Clinical Trials", "PharmD", "Drug Development", "REMS"],
        "is_featured": False,
        "description": "Lead pharmaceutical oversight for our oncology drug development programmes across multiple clinical trial sites.",
        "requirements": "PharmD, BCOP preferred, 7+ years oncology pharmacy including clinical trial experience.",
        "benefits": "Competitive pharma comp, research publications, full benefits.",
    },
    {
        "title": "Chief Nursing Officer",
        "company": "MetroHealth System", "industry": "healthcare",
        "location": "Cleveland, OH", "remote": False,
        "job_type": JobType.full_time, "salary_min": 180000, "salary_max": 240000,
        "skills": ["Nursing Leadership", "Clinical Operations", "Regulatory Compliance", "Budget Management", "Quality Improvement"],
        "is_featured": True,
        "description": "Lead nursing strategy, quality, and operations across our 850-bed hospital system.",
        "requirements": "MSN or DNP required, 10+ years nursing leadership, CNO or equivalent experience.",
        "benefits": "Executive comp package, relocation assistance, comprehensive benefits, CME allowance.",
    },

    # ── Finance (10 jobs) ────────────────────────────────────────────────────
    {
        "title": "Head of FP&A",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 155000, "salary_max": 200000,
        "skills": ["FP&A", "Financial Modeling", "Strategic Planning", "Excel", "Python"],
        "is_featured": True,
        "description": "Own financial planning, forecasting, and business intelligence for a $200M revenue fintech.\n\nResponsibilities\n\n• Lead annual budgeting and quarterly forecasting cycles\n• Build models guiding $50M+ annual technology investment decisions\n• Present board-level financial narratives monthly",
        "requirements": "8+ years FP&A, SaaS or fintech experience required, strong modelling and presentation skills.",
        "benefits": "Equity, bonus, executive exposure, hybrid schedule.",
    },
    {
        "title": "Senior Auditor – Financial Services",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 88000, "salary_max": 120000,
        "skills": ["Internal Audit", "SOX", "Risk Assessment", "Financial Controls", "ACL"],
        "is_featured": False,
        "description": "Execute internal audit engagements across financial controls, IT systems, and operational risk for a regulated fintech.",
        "requirements": "CPA or CIA, 4+ years internal audit, financial services or fintech background preferred.",
        "benefits": "Hybrid, exam support, bonus, career path to audit manager.",
    },
    {
        "title": "Credit Portfolio Manager",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": True,
        "job_type": JobType.full_time, "salary_min": 120000, "salary_max": 160000,
        "skills": ["Credit Risk", "Portfolio Management", "Python", "SQL", "Lending"],
        "is_featured": False,
        "description": "Manage and optimise a $500M consumer credit portfolio across our buy-now-pay-later and personal lending products.",
        "requirements": "5+ years credit portfolio management, Python for analytics required, consumer lending experience.",
        "benefits": "Remote option, strong variable comp, equity.",
    },
    {
        "title": "Fund Accountant – Private Equity",
        "company": "Vault Capital", "industry": "finance",
        "location": "New York, NY", "remote": False,
        "job_type": JobType.full_time, "salary_min": 75000, "salary_max": 100000,
        "skills": ["Fund Accounting", "NAV", "Private Equity", "Excel", "Investran"],
        "is_featured": False,
        "description": "Own fund accounting and NAV calculations for our flagship $800M private equity fund.",
        "requirements": "2+ years fund accounting in PE or fund administration, CPA in progress preferred.",
        "benefits": "Bonus, prestigious brand, career growth into senior fund accounting.",
    },
    {
        "title": "Payments Product Manager",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": True,
        "job_type": JobType.full_time, "salary_min": 130000, "salary_max": 168000,
        "skills": ["Payments", "Product Management", "APIs", "Card Networks", "ACH"],
        "is_featured": False,
        "description": "Define the payments roadmap for our next-generation money movement platform processing $2B+ annually.",
        "requirements": "4+ years PM, payments domain expertise required, card network or ACH knowledge.",
        "benefits": "Remote, equity, high-impact role in fintech growth stage.",
    },
    {
        "title": "ESG Investment Analyst",
        "company": "Vault Capital", "industry": "finance",
        "location": "New York, NY", "remote": False,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 135000,
        "skills": ["ESG", "Impact Investing", "Financial Analysis", "Bloomberg", "Sustainability"],
        "is_featured": False,
        "description": "Integrate ESG factors into investment analysis and support our growing impact investing practice.",
        "requirements": "CFA progress preferred, 2+ years investment analysis, genuine ESG knowledge and passion.",
        "benefits": "Meaningful work, carry potential, top learning environment.",
    },
    {
        "title": "Mortgage Underwriter – Residential",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": True,
        "job_type": JobType.full_time, "salary_min": 72000, "salary_max": 98000,
        "skills": ["Mortgage Underwriting", "DU/LP", "Income Analysis", "Regulatory Compliance", "Credit Analysis"],
        "is_featured": False,
        "description": "Underwrite residential mortgage loans in support of our digital lending platform, ensuring compliance and credit quality.",
        "requirements": "3+ years residential mortgage underwriting, DU/LP expertise, SAFE Act compliance knowledge.",
        "benefits": "Remote, volume bonuses, full benefits.",
    },
    {
        "title": "Director of Finance – Operations",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 140000, "salary_max": 185000,
        "skills": ["Financial Operations", "Controllership", "CPA", "ERP", "GAAP"],
        "is_featured": False,
        "description": "Own the financial close, controllership, and operational finance function for a high-growth fintech company.",
        "requirements": "CPA required, 8+ years finance including controllership, SaaS or fintech preferred.",
        "benefits": "Equity, hybrid, executive visibility, bonus.",
    },
    {
        "title": "Actuarial Analyst",
        "company": "FinTech Partners", "industry": "finance",
        "location": "Austin, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 110000,
        "skills": ["Actuarial Science", "R", "Python", "Reserving", "Pricing"],
        "is_featured": False,
        "description": "Build actuarial models that price our insurance-linked financial products and manage loss reserves.",
        "requirements": "2+ CAS exams passed, 1+ year actuarial experience, strong R or Python skills.",
        "benefits": "Exam support, study time, full benefits, clear progression path.",
    },
    {
        "title": "Wealth Management Associate",
        "company": "Vault Capital", "industry": "finance",
        "location": "New York, NY", "remote": False,
        "job_type": JobType.full_time, "salary_min": 85000, "salary_max": 125000,
        "skills": ["Wealth Management", "Client Relations", "Financial Planning", "CFA", "Estate Planning"],
        "is_featured": False,
        "description": "Support Ultra-High-Net-Worth clients with comprehensive wealth management, planning, and investment advisory services.",
        "requirements": "Series 65 or CFP in progress, 2+ years wealth management, excellent client communication.",
        "benefits": "Bonus, client entertainment budget, CFA exam support.",
    },

    # ── Engineering (10 jobs) ────────────────────────────────────────────────
    {
        "title": "Senior Robotics Engineer",
        "company": "Nimble Manufacturing", "industry": "engineering",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 110000, "salary_max": 148000,
        "skills": ["ROS2", "Python", "C++", "Motion Planning", "Computer Vision"],
        "is_featured": False,
        "description": "Design and program industrial robotics systems for our automated manufacturing production lines.\n\nYou'll work with KUKA and Fanuc robot systems, developing motion planning algorithms and machine vision integrations.",
        "requirements": "BSME or BSCS, 4+ years robotics engineering, ROS or ROS2 experience, C++ required.",
        "benefits": "Cutting-edge robotics projects, full benefits, tuition reimbursement.",
    },
    {
        "title": "Hydrogen Systems Engineer",
        "company": "GreenBridge Energy", "industry": "engineering",
        "location": "Denver, CO", "remote": False,
        "job_type": JobType.full_time, "salary_min": 100000, "salary_max": 138000,
        "skills": ["Hydrogen Technology", "Electrochemistry", "Process Engineering", "HAZOP", "Thermodynamics"],
        "is_featured": True,
        "description": "Pioneer green hydrogen production systems as part of our clean energy diversification strategy.\n\nJoin a small, high-impact team designing electrolysis-based hydrogen production facilities.",
        "requirements": "BS Chemical or Mechanical Engineering, 4+ years energy engineering, hydrogen or fuel cell experience preferred.",
        "benefits": "Mission-driven, equity, relocation assistance, cutting-edge projects.",
    },
    {
        "title": "Energy Storage Engineer",
        "company": "GreenBridge Energy", "industry": "engineering",
        "location": "Denver, CO", "remote": False,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 130000,
        "skills": ["Battery Storage", "BESS", "Power Electronics", "Grid Integration", "Python"],
        "is_featured": False,
        "description": "Design and deploy utility-scale battery energy storage systems integrated with our solar and wind projects.",
        "requirements": "BSEE, 3+ years BESS or power electronics engineering, grid integration experience.",
        "benefits": "Mission-driven company, project bonuses, equity.",
    },
    {
        "title": "Controls Engineer – Automation",
        "company": "Nimble Manufacturing", "industry": "engineering",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 82000, "salary_max": 110000,
        "skills": ["PLC Programming", "Allen Bradley", "HMI", "SCADA", "Siemens"],
        "is_featured": False,
        "description": "Design and program automation systems for our precision manufacturing production lines.\n\nYou'll programme Allen-Bradley and Siemens PLCs, commission new equipment, and support continuous improvement.",
        "requirements": "BSEE or equivalent, 3+ years controls engineering, Allen-Bradley PLC programming required.",
        "benefits": "Overtime, education support, full benefits.",
    },
    {
        "title": "Systems Integration Engineer",
        "company": "TerraNova Builders", "industry": "engineering",
        "location": "Phoenix, AZ", "remote": False,
        "job_type": JobType.full_time, "salary_min": 85000, "salary_max": 115000,
        "skills": ["Systems Integration", "MEP", "BIM", "AutoCAD", "Commissioning"],
        "is_featured": False,
        "description": "Coordinate mechanical, electrical, and plumbing systems integration across our commercial construction portfolio.",
        "requirements": "4+ years MEP systems engineering, BIM experience, commissioning background preferred.",
        "benefits": "Project variety, advancement path, full benefits.",
    },
    {
        "title": "Solar O&M Technician Lead",
        "company": "GreenBridge Energy", "industry": "engineering",
        "location": "Denver, CO", "remote": False,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 88000,
        "skills": ["Solar PV", "O&M", "SCADA", "Electrical Safety", "Inverter Troubleshooting"],
        "is_featured": False,
        "description": "Lead field operations and maintenance for our 500MW portfolio of utility-scale solar facilities across the Southwest.",
        "requirements": "NABCEP certification preferred, 3+ years solar O&M, valid driver's licence, willingness to travel.",
        "benefits": "Company vehicle, per diem, full benefits, growing portfolio.",
    },
    {
        "title": "Geotechnical Engineer",
        "company": "TerraNova Builders", "industry": "engineering",
        "location": "Phoenix, AZ", "remote": False,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["Geotechnical Engineering", "Soil Analysis", "Foundation Design", "SLOPE/W", "Field Investigation"],
        "is_featured": False,
        "description": "Perform geotechnical investigations, analysis, and design for residential and commercial development projects in Arizona.",
        "requirements": "BSCE or Geotechnical, PE license preferred, 3+ years geotechnical practice.",
        "benefits": "Project diversity, PE licensure support, full benefits.",
    },
    {
        "title": "Power Grid Interconnection Engineer",
        "company": "GreenBridge Energy", "industry": "engineering",
        "location": "Denver, CO", "remote": True,
        "job_type": JobType.full_time, "salary_min": 105000, "salary_max": 140000,
        "skills": ["Grid Interconnection", "PSCAD", "IEEE Standards", "Utility Relations", "Power Flow"],
        "is_featured": False,
        "description": "Navigate interconnection processes with utilities and RTOs for our portfolio of renewable energy projects.\n\nYou'll manage interconnection queues, review studies, and negotiate agreements.",
        "requirements": "BSEE, 4+ years grid interconnection experience, PSCAD or PSSE familiarity.",
        "benefits": "Remote-flexible, mission-driven, strong growth path.",
    },
    {
        "title": "Aerospace Structural Analyst",
        "company": "Nimble Manufacturing", "industry": "engineering",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 92000, "salary_max": 125000,
        "skills": ["FEA", "NASTRAN", "Stress Analysis", "Composites", "CATIA"],
        "is_featured": False,
        "description": "Perform structural analysis for aerospace components manufactured at our advanced materials facility.",
        "requirements": "BSME or Aerospace Engineering, 3+ years structural analysis, NASTRAN or ABAQUS required.",
        "benefits": "Government clearance sponsorship, relocation, full benefits.",
    },
    {
        "title": "Senior Piping Engineer",
        "company": "GreenBridge Energy", "industry": "engineering",
        "location": "Denver, CO", "remote": False,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 130000,
        "skills": ["Piping Design", "ASME Codes", "Caesar II", "P&IDs", "Stress Analysis"],
        "is_featured": False,
        "description": "Design piping systems for our hydrogen and biogas facilities, ensuring code compliance and operational safety.",
        "requirements": "BS Mechanical Engineering, PE preferred, 5+ years piping design in energy or chemical industry.",
        "benefits": "Relocation assistance, full benefits, growing energy portfolio.",
    },

    # ── Marketing (10 jobs) ──────────────────────────────────────────────────
    {
        "title": "VP of Marketing",
        "company": "PrimeCast Media", "industry": "marketing",
        "location": "New York, NY", "remote": False,
        "job_type": JobType.full_time, "salary_min": 160000, "salary_max": 220000,
        "skills": ["Marketing Leadership", "Brand Strategy", "Demand Generation", "Team Management", "Analytics"],
        "is_featured": True,
        "description": "Lead all marketing functions for a fast-growing media company reaching 20M monthly readers.\n\nYou'll own brand, content, performance, and audience development, managing a team of 15.",
        "requirements": "10+ years marketing leadership, media or digital background strongly preferred.",
        "benefits": "Equity, executive package, media perks.",
    },
    {
        "title": "Head of Influencer Marketing",
        "company": "PrimeCast Media", "industry": "marketing",
        "location": "New York, NY", "remote": True,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 130000,
        "skills": ["Influencer Marketing", "Creator Partnerships", "Campaign Management", "Analytics", "Negotiation"],
        "is_featured": False,
        "description": "Build and scale our influencer marketing programme, partnering with 500+ creators to drive brand awareness.",
        "requirements": "5+ years influencer or creator partnerships, strong negotiation, media or DTC background.",
        "benefits": "Remote, performance bonus, creator network access.",
    },
    {
        "title": "Growth Marketing Manager",
        "company": "DataFlow Inc.", "industry": "marketing",
        "location": "San Francisco, CA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 105000, "salary_max": 140000,
        "skills": ["Growth Marketing", "A/B Testing", "Email", "Paid Acquisition", "Analytics"],
        "is_featured": False,
        "description": "Own growth marketing for DataFlow's self-serve product, driving acquisition, activation, and retention across a $5M annual spend.",
        "requirements": "4+ years growth marketing in SaaS, strong data analysis, multi-channel expertise.",
        "benefits": "Remote, equity, high-impact role.",
    },
    {
        "title": "B2B Content Strategist",
        "company": "Acme Technologies", "industry": "marketing",
        "location": "New York, NY", "remote": True,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["Content Strategy", "SEO", "Thought Leadership", "Copywriting", "HubSpot"],
        "is_featured": False,
        "description": "Develop content that establishes Acme as a thought leader in enterprise technology and drives pipeline for our sales team.",
        "requirements": "4+ years B2B content marketing, technical writing ability, SEO expertise, enterprise software background.",
        "benefits": "Remote-friendly, creative freedom, performance bonus.",
    },
    {
        "title": "Demand Generation Manager",
        "company": "CloudNative Corp", "industry": "marketing",
        "location": "Seattle, WA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 128000,
        "skills": ["Demand Generation", "HubSpot", "ABM", "Webinars", "Marketing Automation"],
        "is_featured": False,
        "description": "Drive qualified pipeline for our enterprise cloud platform through ABM, events, and digital demand gen programmes.",
        "requirements": "4+ years B2B demand gen, HubSpot or Marketo required, ABM experience strongly preferred.",
        "benefits": "Remote, events budget, equity, growth path.",
    },
    {
        "title": "Marketing Analytics Manager",
        "company": "RetailNext", "industry": "marketing",
        "location": "Atlanta, GA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 90000, "salary_max": 120000,
        "skills": ["Marketing Analytics", "SQL", "Tableau", "Attribution Modeling", "Python"],
        "is_featured": False,
        "description": "Turn marketing data into actionable insights that optimise spend across channels and maximise customer LTV.",
        "requirements": "4+ years marketing analytics, strong SQL and Python, multi-touch attribution experience.",
        "benefits": "Remote, analytical culture, performance bonus.",
    },
    {
        "title": "Communications Director",
        "company": "GreenBridge Energy", "industry": "marketing",
        "location": "Denver, CO", "remote": False,
        "job_type": JobType.full_time, "salary_min": 120000, "salary_max": 160000,
        "skills": ["Corporate Communications", "PR", "Media Relations", "Executive Communications", "Crisis Communications"],
        "is_featured": False,
        "description": "Lead external and internal communications for a mission-driven renewable energy company.",
        "requirements": "8+ years corporate communications, energy or infrastructure background preferred.",
        "benefits": "Mission-driven, equity, hybrid schedule.",
    },
    {
        "title": "Product Marketing Manager – Enterprise",
        "company": "CloudNative Corp", "industry": "marketing",
        "location": "Seattle, WA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 115000, "salary_max": 155000,
        "skills": ["Product Marketing", "Positioning", "Competitive Analysis", "Enablement", "GTM"],
        "is_featured": False,
        "description": "Own product marketing for our enterprise cloud platform, defining positioning, building sales enablement, and driving GTM strategy.",
        "requirements": "4+ years product marketing in enterprise SaaS, strong storytelling and competitive analysis skills.",
        "benefits": "Remote, equity, strategic influence.",
    },
    {
        "title": "Event Marketing Manager",
        "company": "DataFlow Inc.", "industry": "marketing",
        "location": "San Francisco, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 108000,
        "skills": ["Event Marketing", "Trade Shows", "Budget Management", "Salesforce", "Demand Gen"],
        "is_featured": False,
        "description": "Own DataFlow's event strategy — from industry conferences to our flagship annual user conference with 2,000+ attendees.",
        "requirements": "4+ years B2B event marketing, large conference management experience, budget ownership.",
        "benefits": "Travel stipend, event perks, cross-functional impact.",
    },
    {
        "title": "CRM Manager",
        "company": "RetailNext", "industry": "marketing",
        "location": "Atlanta, GA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 72000, "salary_max": 98000,
        "skills": ["CRM", "Klaviyo", "Email Marketing", "Segmentation", "Customer Lifecycle"],
        "is_featured": False,
        "description": "Build and optimise our CRM programme to drive repeat purchase and increase customer LTV across our retail brands.",
        "requirements": "3+ years CRM or email marketing, Klaviyo or Braze expertise, retail or DTC background.",
        "benefits": "Remote, performance bonus, creative scope.",
    },

    # ── Education (10 jobs) ──────────────────────────────────────────────────
    {
        "title": "Director of Online Programs",
        "company": "EduPath Learning", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 110000, "salary_max": 148000,
        "skills": ["Online Education", "Program Management", "LMS", "Enrollment Strategy", "Accreditation"],
        "is_featured": True,
        "description": "Lead strategy and operations for EduPath's portfolio of 40+ online certificate and degree programmes.\n\nYou'll oversee program quality, instructor relationships, and learner outcomes.",
        "requirements": "7+ years online education leadership, LMS expertise, accreditation experience preferred.",
        "benefits": "100% remote, meaningful mission, executive team visibility.",
    },
    {
        "title": "Special Education Teacher – Virtual",
        "company": "BrightMinds Academy", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 52000, "salary_max": 72000,
        "skills": ["Special Education", "IEP Development", "Assistive Technology", "Differentiated Instruction", "Behavior Management"],
        "is_featured": False,
        "description": "Provide high-quality virtual special education instruction and IEP services for students with diverse learning needs.",
        "requirements": "Special education certification, 2+ years classroom experience, virtual teaching experience preferred.",
        "benefits": "Remote, flexible hours, team support, meaningful impact.",
    },
    {
        "title": "Corporate Trainer – Leadership",
        "company": "Nimble Manufacturing", "industry": "education",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 68000, "salary_max": 92000,
        "skills": ["Leadership Training", "Facilitation", "Instructional Design", "Coaching", "Change Management"],
        "is_featured": False,
        "description": "Design and deliver leadership development programmes for our 200 frontline and mid-level manufacturing managers.",
        "requirements": "5+ years corporate training, leadership development expertise, manufacturing environment preferred.",
        "benefits": "Tuition reimbursement, career growth, full benefits.",
    },
    {
        "title": "LMS Administrator",
        "company": "EduPath Learning", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 58000, "salary_max": 80000,
        "skills": ["LMS Administration", "Canvas", "Moodle", "Technical Support", "Data Reporting"],
        "is_featured": False,
        "description": "Manage and optimise our Canvas LMS environment, supporting 500K+ active learners and 2,000 instructors.",
        "requirements": "3+ years LMS administration, Canvas certified preferred, strong technical troubleshooting skills.",
        "benefits": "100% remote, great team, professional development.",
    },
    {
        "title": "EdTech Sales Executive",
        "company": "EduPath Learning", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 140000,
        "skills": ["EdTech Sales", "SaaS Sales", "K-12", "District Sales", "CRM"],
        "is_featured": False,
        "description": "Drive revenue by selling EduPath's platform to school districts, community colleges, and corporate L&D departments.",
        "requirements": "3+ years EdTech or SaaS sales, K-12 district sales experience preferred, consistent quota attainment.",
        "benefits": "Uncapped OTE, remote, meaningful product.",
    },
    {
        "title": "University Partnerships Manager",
        "company": "EduPath Learning", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 110000,
        "skills": ["Partnerships", "Higher Education", "Business Development", "Contract Negotiation", "Relationship Management"],
        "is_featured": False,
        "description": "Develop and grow EduPath's network of university content partnerships, bringing world-class courses to our platform.",
        "requirements": "4+ years partnerships or business development, higher education background a strong plus.",
        "benefits": "Remote, equity, mission-driven culture.",
    },
    {
        "title": "Assessment & Evaluation Specialist",
        "company": "BrightMinds Academy", "industry": "education",
        "location": "Boston, MA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 88000,
        "skills": ["Educational Assessment", "Data Analysis", "Psychometrics", "NWEA", "School Improvement"],
        "is_featured": False,
        "description": "Lead student assessment strategy, data analysis, and school improvement planning across our K-12 programmes.",
        "requirements": "Master's in Education or Psychometrics, 3+ years assessment leadership, data analysis skills.",
        "benefits": "Summer schedule, professional development budget, tuition for dependents.",
    },
    {
        "title": "Foreign Language Teacher – Mandarin",
        "company": "BrightMinds Academy", "industry": "education",
        "location": "Boston, MA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 50000, "salary_max": 70000,
        "skills": ["Mandarin Chinese", "Language Teaching", "Curriculum Design", "Cultural Education", "Proficiency Assessment"],
        "is_featured": False,
        "description": "Teach Mandarin Chinese to grades 4-12 in our internationally focused college-preparatory curriculum.",
        "requirements": "Native or near-native Mandarin proficiency, teaching certification, 2+ years language instruction.",
        "benefits": "Summers off, tuition benefit for dependents, cultural environment.",
    },
    {
        "title": "Head of Instructional Design",
        "company": "EduPath Learning", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 110000, "salary_max": 148000,
        "skills": ["Instructional Design", "Team Leadership", "Curriculum Strategy", "Learning Science", "eLearning"],
        "is_featured": False,
        "description": "Lead EduPath's 20-person instructional design team, setting standards for learning experience quality across our platform.",
        "requirements": "7+ years instructional design, 3+ years team leadership, strong learning science background.",
        "benefits": "100% remote, equity, executive team.",
    },
    {
        "title": "STEM Curriculum Developer",
        "company": "BrightMinds Academy", "industry": "education",
        "location": "Remote", "remote": True,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 88000,
        "skills": ["STEM Education", "Curriculum Design", "Python", "Project-Based Learning", "Standards Alignment"],
        "is_featured": False,
        "description": "Design rigorous, engaging STEM curriculum for grades 6-12 that integrates coding, engineering, and scientific inquiry.",
        "requirements": "STEM teaching background, 3+ years curriculum development.",
        "benefits": "Remote, creative work, meaningful mission.",
    },

    # ── Legal (10 jobs) ──────────────────────────────────────────────────────
    {
        "title": "General Counsel",
        "company": "FinTech Partners", "industry": "legal",
        "location": "Austin, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 200000, "salary_max": 280000,
        "skills": ["Corporate Law", "Regulatory Compliance", "M&A", "Fintech", "Securities Law"],
        "is_featured": True,
        "description": "Serve as the top legal officer for a $200M revenue fintech company, overseeing regulatory compliance, corporate transactions, and legal risk management.",
        "requirements": "JD from top law school, 12+ years legal experience including in-house counsel leadership, fintech or financial services required.",
        "benefits": "Executive comp, equity, board visibility.",
    },
    {
        "title": "Regulatory Affairs Attorney",
        "company": "NovaBio Labs", "industry": "legal",
        "location": "Boston, MA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 130000, "salary_max": 175000,
        "skills": ["FDA", "Drug Regulation", "Clinical Trials", "Biotech Law", "Regulatory Strategy"],
        "is_featured": False,
        "description": "Provide legal guidance on FDA regulatory strategy for our oncology drug pipeline, from IND through BLA.",
        "requirements": "JD, 5+ years pharmaceutical regulatory law, FDA experience required.",
        "benefits": "Remote option, biotech equity, professional development.",
    },
    {
        "title": "Commercial Real Estate Attorney",
        "company": "LexaCorp Legal", "industry": "legal",
        "location": "Chicago, IL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 140000, "salary_max": 190000,
        "skills": ["Commercial Real Estate", "Lease Negotiation", "Acquisition", "Title Review", "Development"],
        "is_featured": False,
        "description": "Represent institutional clients in commercial real estate acquisitions, dispositions, leasing, and development transactions.",
        "requirements": "JD, 4+ years commercial real estate transactional experience, IL bar admission.",
        "benefits": "Billable bonus, deal variety, prestigious clients.",
    },
    {
        "title": "Patent Attorney – Software",
        "company": "Nexus Law Group", "industry": "legal",
        "location": "Washington, DC", "remote": True,
        "job_type": JobType.full_time, "salary_min": 155000, "salary_max": 210000,
        "skills": ["Patent Law", "Software Patents", "USPTO", "Patent Prosecution", "Technical Writing"],
        "is_featured": False,
        "description": "Prosecute software and AI patents for leading technology company clients, from application drafting through USPTO examination.",
        "requirements": "JD + CS or EE technical background, USPTO registration, 3+ years software patent prosecution.",
        "benefits": "Remote-friendly, strong comp, prestigious tech clients.",
    },
    {
        "title": "Labor & Employment Attorney",
        "company": "LexaCorp Legal", "industry": "legal",
        "location": "Chicago, IL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 115000, "salary_max": 160000,
        "skills": ["Labor Law", "Employment Litigation", "NLRA", "Class Actions", "Arbitration"],
        "is_featured": False,
        "description": "Represent employers in labour disputes, NLRB proceedings, wage and hour class actions, and employment litigation.",
        "requirements": "JD, 3+ years labour and employment litigation, IL bar, trial experience preferred.",
        "benefits": "Litigation variety, billable bonus, professional development.",
    },
    {
        "title": "Legal Project Manager",
        "company": "LexaCorp Legal", "industry": "legal",
        "location": "Chicago, IL", "remote": True,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 108000,
        "skills": ["Legal Project Management", "Matter Management", "Budgeting", "Process Improvement", "Legal Tech"],
        "is_featured": False,
        "description": "Lead matter management, legal project planning, and process improvement initiatives across our litigation and transactional practices.",
        "requirements": "4+ years legal project management, CLPM certification preferred, legal tech proficiency.",
        "benefits": "Remote-friendly, growing LPM function, competitive comp.",
    },
    {
        "title": "Health Law Attorney",
        "company": "Nexus Law Group", "industry": "legal",
        "location": "Washington, DC", "remote": True,
        "job_type": JobType.full_time, "salary_min": 120000, "salary_max": 165000,
        "skills": ["Health Law", "HIPAA", "Medicare", "Regulatory Compliance", "Healthcare Contracts"],
        "is_featured": False,
        "description": "Advise hospitals, health systems, and digital health companies on regulatory compliance, payor contracting, and HIPAA matters.",
        "requirements": "JD, DC or VA bar, 4+ years health law, regulatory compliance background.",
        "benefits": "Remote option, growing practice, hybrid schedule.",
    },
    {
        "title": "Contracts Manager",
        "company": "Acme Technologies", "industry": "legal",
        "location": "New York, NY", "remote": True,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 128000,
        "skills": ["Contract Management", "SaaS Agreements", "Redlining", "CLM Software", "Negotiation"],
        "is_featured": False,
        "description": "Own the end-to-end commercial contracts function for a $300M SaaS company — from template development to complex enterprise negotiations.",
        "requirements": "4+ years contracts management, SaaS or tech industry, JD a plus but not required.",
        "benefits": "Remote, equity, high-throughput contracts environment.",
    },
    {
        "title": "Environmental Compliance Counsel",
        "company": "GreenBridge Energy", "industry": "legal",
        "location": "Denver, CO", "remote": True,
        "job_type": JobType.full_time, "salary_min": 130000, "salary_max": 175000,
        "skills": ["Environmental Law", "NEPA", "Clean Air Act", "Permitting", "Regulatory Compliance"],
        "is_featured": False,
        "description": "Provide environmental legal counsel for our portfolio of utility-scale renewable energy projects across the US.",
        "requirements": "JD, 5+ years environmental law, energy project permitting experience required.",
        "benefits": "Mission-driven, remote-flexible, strong comp.",
    },
    {
        "title": "Privacy Compliance Manager",
        "company": "DataFlow Inc.", "industry": "legal",
        "location": "San Francisco, CA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 105000, "salary_max": 140000,
        "skills": ["GDPR", "CCPA", "Privacy Compliance", "Data Governance", "OneTrust"],
        "is_featured": False,
        "description": "Build and operate our global privacy compliance programme across GDPR, CCPA, and emerging state privacy laws.",
        "requirements": "CIPP/US or CIPP/E required, 4+ years privacy compliance, SaaS or cloud company experience.",
        "benefits": "Remote-first, equity, cutting-edge privacy work.",
    },

    # ── Retail (10 jobs) ─────────────────────────────────────────────────────
    {
        "title": "Chief Merchandising Officer",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 200000, "salary_max": 270000,
        "skills": ["Merchandising Strategy", "Buying", "Category Management", "P&L", "Trend Analysis"],
        "is_featured": True,
        "description": "Lead all merchandising strategy and buying for a 300-store retail chain with $1B+ annual revenue.",
        "requirements": "12+ years retail merchandising leadership, proven P&L ownership, multi-category experience.",
        "benefits": "Executive comp, equity, significant business impact.",
    },
    {
        "title": "Inventory Planner – Electronics",
        "company": "RetailNext", "industry": "retail",
        "location": "Atlanta, GA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 62000, "salary_max": 85000,
        "skills": ["Demand Planning", "Inventory Management", "Excel", "SAP", "Open-to-Buy"],
        "is_featured": False,
        "description": "Manage inventory planning for our high-velocity electronics category across 200+ stores and our DTC channel.",
        "requirements": "2+ years inventory planning, retail math proficiency, SAP or Oracle experience.",
        "benefits": "Remote, employee discount, career growth.",
    },
    {
        "title": "Customer Experience Manager",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 70000, "salary_max": 95000,
        "skills": ["Customer Experience", "Net Promoter Score", "Service Design", "Training", "Voice of Customer"],
        "is_featured": False,
        "description": "Design and embed a superior customer experience across our store network, driving NPS improvement and repeat visits.",
        "requirements": "4+ years CX management, retail environment, training programme design experience.",
        "benefits": "Bonus on NPS targets, company discount, full benefits.",
    },
    {
        "title": "Franchise Operations Manager",
        "company": "RetailNext", "industry": "retail",
        "location": "Atlanta, GA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 85000, "salary_max": 115000,
        "skills": ["Franchise Management", "Field Operations", "Training", "Compliance Auditing", "P&L Support"],
        "is_featured": False,
        "description": "Support and develop our network of 150 franchise partners, driving operational excellence, brand compliance, and sales growth.",
        "requirements": "4+ years franchise or multi-unit operations management, retail background.",
        "benefits": "Travel stipend, bonus, diverse markets exposure.",
    },
    {
        "title": "Fashion Buyer – Accessories",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 68000, "salary_max": 92000,
        "skills": ["Fashion Buying", "Accessories", "Trend Forecasting", "Vendor Negotiation", "Open-to-Buy"],
        "is_featured": False,
        "description": "Build a commercially compelling accessories assortment — handbags, jewellery, and footwear — for our 300-store fashion retail chain.",
        "requirements": "3+ years fashion buying, accessories category experience, strong trend and market awareness.",
        "benefits": "Merchandise discount, Paris trade show travel, growth path.",
    },
    {
        "title": "eCommerce UX Designer",
        "company": "RetailNext", "industry": "retail",
        "location": "Atlanta, GA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["UX Design", "Figma", "eCommerce", "Conversion Optimisation", "User Research"],
        "is_featured": False,
        "description": "Design and optimise the end-to-end shopping experience on our DTC platform, improving conversion and reducing cart abandonment.",
        "requirements": "3+ years UX design with eCommerce portfolio, Figma proficiency, A/B testing mindset.",
        "benefits": "Remote, creative autonomy, performance bonus.",
    },
    {
        "title": "Pricing Strategy Analyst",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": True,
        "job_type": JobType.full_time, "salary_min": 72000, "salary_max": 98000,
        "skills": ["Pricing Strategy", "SQL", "Python", "Competitive Analysis", "Excel"],
        "is_featured": False,
        "description": "Build pricing models and competitive pricing strategies that maximise revenue and margin across our 50,000 SKU assortment.",
        "requirements": "2+ years pricing analytics, retail domain preferred, SQL and Python required.",
        "benefits": "Remote-friendly, analytical culture, performance bonus.",
    },
    {
        "title": "Director of Private Label",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 130000, "salary_max": 170000,
        "skills": ["Private Label", "Product Development", "Sourcing", "Vendor Management", "Brand Strategy"],
        "is_featured": False,
        "description": "Lead the development and launch of our owned brand portfolio, growing private label penetration from 12% to 25% of total revenue.",
        "requirements": "8+ years private label or product development in retail, P&L management experience.",
        "benefits": "Equity, executive exposure, high-impact role.",
    },
    {
        "title": "Retail Training Specialist",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 52000, "salary_max": 70000,
        "skills": ["Retail Training", "Onboarding", "Product Knowledge", "Sales Techniques", "LMS"],
        "is_featured": False,
        "description": "Develop and deliver training programmes for 2,000+ store associates, improving product knowledge, selling skills, and customer service.",
        "requirements": "3+ years retail training, strong facilitation skills, LMS content creation experience.",
        "benefits": "Travel, merchandise discount, career growth.",
    },
    {
        "title": "Retail Real Estate Analyst",
        "company": "Urban Store Co.", "industry": "retail",
        "location": "Los Angeles, CA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 90000,
        "skills": ["Real Estate Analysis", "Market Research", "GIS", "Lease Negotiation Support", "Financial Modeling"],
        "is_featured": False,
        "description": "Support our real estate team in evaluating new store locations, renewals, and closures across our national footprint.",
        "requirements": "2+ years retail real estate or real estate analysis, GIS and Excel proficiency.",
        "benefits": "Travel, growth company, full benefits.",
    },

    # ── Logistics (10 jobs) ──────────────────────────────────────────────────
    {
        "title": "Head of Supply Chain Strategy",
        "company": "Alpha Logistics", "industry": "logistics",
        "location": "Chicago, IL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 150000, "salary_max": 200000,
        "skills": ["Supply Chain Strategy", "Network Design", "Digital Transformation", "Analytics", "Leadership"],
        "is_featured": True,
        "description": "Define and drive Alpha Logistics' 5-year supply chain transformation strategy, modernising our network of 25 distribution centres.",
        "requirements": "10+ years supply chain leadership, network design experience, consulting background a plus.",
        "benefits": "Executive comp, equity, board-level visibility.",
    },
    {
        "title": "Reverse Logistics Manager",
        "company": "SwiftLogix", "industry": "logistics",
        "location": "Dallas, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 75000, "salary_max": 100000,
        "skills": ["Reverse Logistics", "Returns Processing", "Warehouse Operations", "ERP", "Cost Reduction"],
        "is_featured": False,
        "description": "Build and optimise our reverse logistics operation, managing returns processing for 10M+ items annually.",
        "requirements": "4+ years reverse logistics management, warehouse operations experience, ERP proficiency.",
        "benefits": "Profit sharing, full benefits, fast-growing division.",
    },
    {
        "title": "Customs Compliance Specialist",
        "company": "Alpha Logistics", "industry": "logistics",
        "location": "Chicago, IL", "remote": True,
        "job_type": JobType.full_time, "salary_min": 65000, "salary_max": 88000,
        "skills": ["Customs Compliance", "HTS Codes", "Duty Drawback", "Import/Export", "ACE Portal"],
        "is_featured": False,
        "description": "Ensure regulatory compliance for our cross-border shipments, managing HTS classification, duty drawback programmes, and C-TPAT compliance.",
        "requirements": "3+ years customs compliance, licensed customs broker preferred, ACE portal experience.",
        "benefits": "Remote-friendly, specialised career, full benefits.",
    },
    {
        "title": "E-Commerce Fulfillment Manager",
        "company": "SwiftLogix", "industry": "logistics",
        "location": "Dallas, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 108000,
        "skills": ["eCommerce Fulfillment", "WMS", "SLA Management", "Carrier Relationships", "Peak Planning"],
        "is_featured": False,
        "description": "Lead our dedicated e-commerce fulfilment operation, managing 100K+ orders per day across our three DFW fulfilment centres.",
        "requirements": "5+ years e-commerce fulfilment management, WMS expertise, peak season planning experience.",
        "benefits": "Bonus on SLA attainment, full benefits, fast-growing channel.",
    },
    {
        "title": "Transportation Analyst",
        "company": "Alpha Logistics", "industry": "logistics",
        "location": "Chicago, IL", "remote": True,
        "job_type": JobType.full_time, "salary_min": 60000, "salary_max": 82000,
        "skills": ["Transportation Analytics", "TMS", "SQL", "Lane Costing", "Carrier Analytics"],
        "is_featured": False,
        "description": "Analyse carrier performance, transportation costs, and lane profitability to optimise our $500M freight spend.",
        "requirements": "2+ years transportation analytics, TMS experience, strong SQL and Excel skills.",
        "benefits": "Remote, analytical culture, career growth path.",
    },
    {
        "title": "Intermodal Operations Manager",
        "company": "SwiftLogix", "industry": "logistics",
        "location": "Dallas, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 82000, "salary_max": 112000,
        "skills": ["Intermodal", "Rail Freight", "Container Management", "Drayage", "Operations"],
        "is_featured": False,
        "description": "Manage our intermodal operations across the I-10 and I-20 corridors, optimising rail and drayage for 500+ containers per month.",
        "requirements": "4+ years intermodal operations, rail carrier relationships, drayage management experience.",
        "benefits": "Competitive comp, full benefits, growing intermodal division.",
    },
    {
        "title": "Demand Planning Manager",
        "company": "Alpha Logistics", "industry": "logistics",
        "location": "Chicago, IL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 90000, "salary_max": 120000,
        "skills": ["Demand Planning", "S&OP", "Statistical Forecasting", "SAP APO", "Cross-functional Collaboration"],
        "is_featured": False,
        "description": "Lead demand planning and S&OP processes for our 3PL clients in the consumer goods and retail sectors.",
        "requirements": "5+ years demand planning, APICS CPIM preferred, SAP APO or o9 experience.",
        "benefits": "Profit sharing, hybrid schedule, full benefits.",
    },
    {
        "title": "Ocean Freight Manager",
        "company": "Alpha Logistics", "industry": "logistics",
        "location": "Chicago, IL", "remote": False,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["Ocean Freight", "Container Shipping", "NVOCC", "Incoterms", "Carrier Negotiations"],
        "is_featured": False,
        "description": "Manage our ocean freight procurement and operations for transpacific and transatlantic lanes serving 200+ clients.",
        "requirements": "5+ years ocean freight, NVOCC operations experience, strong carrier relationships.",
        "benefits": "International scope, full benefits, career growth.",
    },
    {
        "title": "Logistics Software Implementation Lead",
        "company": "SwiftLogix", "industry": "logistics",
        "location": "Dallas, TX", "remote": True,
        "job_type": JobType.full_time, "salary_min": 95000, "salary_max": 128000,
        "skills": ["WMS Implementation", "TMS", "Project Management", "Business Analysis", "Training"],
        "is_featured": False,
        "description": "Lead the implementation of our new Manhattan WMS across 5 distribution centres, managing data migration, training, and go-live.",
        "requirements": "4+ years WMS/TMS implementation, project management, logistics domain knowledge.",
        "benefits": "Remote project work, implementation bonus, tech-forward company.",
    },
    {
        "title": "Yard Management Coordinator",
        "company": "SwiftLogix", "industry": "logistics",
        "location": "Dallas, TX", "remote": False,
        "job_type": JobType.full_time, "salary_min": 48000, "salary_max": 65000,
        "skills": ["Yard Management", "Trailer Tracking", "Safety", "WMS", "Driver Communication"],
        "is_featured": False,
        "description": "Coordinate inbound and outbound trailer movements, dock scheduling, and yard inventory for our 300-door Dallas fulfilment centre.",
        "requirements": "2+ years yard management or warehouse operations, YMS or WMS experience preferred.",
        "benefits": "Shift differential, full benefits, overtime opportunities.",
    },

    # ── Manufacturing (10 jobs) ──────────────────────────────────────────────
    {
        "title": "VP of Manufacturing Operations",
        "company": "SteelCraft Industries", "industry": "manufacturing",
        "location": "Pittsburgh, PA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 180000, "salary_max": 240000,
        "skills": ["Manufacturing Leadership", "P&L", "Lean", "Capital Projects", "Multi-site Operations"],
        "is_featured": True,
        "description": "Lead manufacturing operations across three SteelCraft facilities totalling 700,000 sq ft and 900 employees.\n\nYou'll drive OEE improvement, capital investment, and a culture of operational excellence.",
        "requirements": "15+ years manufacturing leadership, P&L ownership, multi-site management experience.",
        "benefits": "Executive comp, profit sharing, relocation assistance.",
    },
    {
        "title": "Tooling Engineer",
        "company": "Nimble Manufacturing", "industry": "manufacturing",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 75000, "salary_max": 100000,
        "skills": ["Tooling Design", "SolidWorks", "Die Design", "Press Tools", "DFM"],
        "is_featured": False,
        "description": "Design, develop, and maintain tooling and fixtures for our precision stamping and machining operations.",
        "requirements": "BSME, 3+ years tooling design, die or press tool experience, SolidWorks required.",
        "benefits": "Patent support, full benefits, tuition reimbursement.",
    },
    {
        "title": "Metallurgical Engineer",
        "company": "SteelCraft Industries", "industry": "manufacturing",
        "location": "Pittsburgh, PA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 85000, "salary_max": 115000,
        "skills": ["Metallurgy", "Steel Processing", "Failure Analysis", "Heat Treatment", "Weld Metallurgy"],
        "is_featured": False,
        "description": "Provide metallurgical expertise for our structural steel fabrication, supporting product development, quality, and failure investigation.",
        "requirements": "BS Metallurgical Engineering or Materials Science, 3+ years steel or metals manufacturing.",
        "benefits": "Technical depth, full benefits, stable company.",
    },
    {
        "title": "Continuous Improvement Manager",
        "company": "Nimble Manufacturing", "industry": "manufacturing",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 90000, "salary_max": 120000,
        "skills": ["Lean Six Sigma", "Value Stream Mapping", "Kaizen", "OEE Improvement", "Change Management"],
        "is_featured": False,
        "description": "Lead our Lean transformation, facilitating kaizen events and deploying Six Sigma tools to achieve our 20% productivity improvement target.",
        "requirements": "Lean Six Sigma Black Belt required, 5+ years CI in automotive or aerospace manufacturing.",
        "benefits": "Leadership track, full benefits, impactful role.",
    },
    {
        "title": "Plastics Process Engineer",
        "company": "Nimble Manufacturing", "industry": "manufacturing",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["Injection Molding", "Process Optimization", "Scientific Molding", "DOE", "SPC"],
        "is_featured": False,
        "description": "Optimise injection moulding processes for high-precision automotive interior components.\n\nYou'll use scientific moulding principles and DOE to achieve zero-defect production.",
        "requirements": "3+ years injection moulding process engineering, automotive or medical plastics preferred.",
        "benefits": "Technical environment, tuition support, full benefits.",
    },
    {
        "title": "Facilities Manager – Manufacturing",
        "company": "SteelCraft Industries", "industry": "manufacturing",
        "location": "Pittsburgh, PA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 75000, "salary_max": 100000,
        "skills": ["Facilities Management", "Capital Projects", "HVAC", "Building Systems", "Safety Compliance"],
        "is_featured": False,
        "description": "Manage facilities, capital improvement projects, and building systems for our 250,000 sq ft steel fabrication plant.",
        "requirements": "5+ years facilities management in industrial settings, capital project experience required.",
        "benefits": "Full benefits, stable company, leadership scope.",
    },
    {
        "title": "Production Scheduler",
        "company": "SteelCraft Industries", "industry": "manufacturing",
        "location": "Pittsburgh, PA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 58000, "salary_max": 78000,
        "skills": ["Production Scheduling", "ERP", "MRP", "Capacity Planning", "Excel"],
        "is_featured": False,
        "description": "Develop and manage production schedules to ensure on-time delivery for our fabrication customers, balancing capacity and material availability.",
        "requirements": "2+ years production scheduling in manufacturing, ERP/MRP experience, strong attention to detail.",
        "benefits": "Stable shifts, full benefits, career growth.",
    },
    {
        "title": "Automated Welding Technician",
        "company": "SteelCraft Industries", "industry": "manufacturing",
        "location": "Pittsburgh, PA", "remote": False,
        "job_type": JobType.full_time, "salary_min": 55000, "salary_max": 75000,
        "skills": ["Robotic Welding", "Fanuc", "GMAW", "Blueprint Reading", "Fixture Setup"],
        "is_featured": False,
        "description": "Operate and maintain Fanuc robotic welding cells for our structural steel fabrication production line.",
        "requirements": "3+ years robotic or automated welding experience, Fanuc controller programming preferred.",
        "benefits": "Skilled trade premium, overtime, full benefits.",
    },
    {
        "title": "Quality Engineer – Aerospace",
        "company": "Nimble Manufacturing", "industry": "manufacturing",
        "location": "Detroit, MI", "remote": False,
        "job_type": JobType.full_time, "salary_min": 80000, "salary_max": 110000,
        "skills": ["AS9100", "First Article Inspection", "PPAP", "CMM", "Root Cause Analysis"],
        "is_featured": False,
        "description": "Lead quality assurance for aerospace component production, ensuring compliance with AS9100 and customer-specific requirements.",
        "requirements": "3+ years aerospace quality engineering, AS9100 auditor preferred, PPAP expertise.",
        "benefits": "Security-cleared projects eligible, full benefits, tuition support.",
    },
    {
        "title": "Supply Quality Engineer",
        "company": "Nimble Manufacturing", "industry": "manufacturing",
        "location": "Detroit, MI", "remote": True,
        "job_type": JobType.full_time, "salary_min": 78000, "salary_max": 105000,
        "skills": ["Supplier Quality", "PPAP", "APQP", "Supplier Development", "Auditing"],
        "is_featured": False,
        "description": "Develop and qualify our supplier base, conducting audits, reviewing PPAPs, and driving corrective actions to ensure incoming part quality.",
        "requirements": "3+ years supplier quality engineering, automotive PPAP expertise, auditing skills.",
        "benefits": "Travel to supplier sites, full benefits, engineering growth.",
    },
]


# ── DB insertion ──────────────────────────────────────────────────────────────

async def run():
    async with Session() as db:
        # Load industry map
        from sqlalchemy import select as sa_select
        from app.models.models import Industry as IndustryModel
        industries = (await db.scalars(sa_select(IndustryModel))).all()
        if not industries:
            print("❌  No industries found — run seed.py first.")
            return
        industry_map = {ind.slug: ind.id for ind in industries}

        # Shuffle so repeated runs insert in varied order
        pool = list(JOBS_POOL)
        random.shuffle(pool)

        company_cache: dict[str, int] = {}
        inserted = 0
        skipped = 0
        category_counts: dict[str, int] = {}

        for jd in pool:
            co_name = jd["company"]
            ind_slug = jd["industry"]
            ind_id = industry_map.get(ind_slug, industry_map.get("technology"))

            # Resolve / create company
            if co_name not in company_cache:
                company = await db.scalar(
                    select(Company).where(Company.name == co_name)
                )
                if not company:
                    slug = to_slug(co_name)
                    if await db.scalar(select(Company).where(Company.slug == slug)):
                        slug = f"{slug}-ext"
                    company = Company(
                        name=co_name,
                        slug=slug,
                        industry_id=ind_id,
                        is_verified=True,
                        headquarters=jd["location"],
                    )
                    db.add(company)
                    await db.flush()
                company_cache[co_name] = company.id

            company_id = company_cache[co_name]

            # Skip duplicates
            exists = await db.scalar(
                select(Job).where(
                    Job.title == jd["title"],
                    Job.company_id == company_id,
                )
            )
            if exists:
                skipped += 1
                continue

            # Unique slug
            base_slug = to_slug(jd["title"])
            job_slug = f"{base_slug}-{company_id}"
            if await db.scalar(select(Job).where(Job.slug == job_slug)):
                job_slug = f"{job_slug}-{inserted}"

            # Stagger created_at so newer seeds appear fresh on the board
            days_ago = random.randint(0, 14)
            created = datetime.utcnow() - timedelta(days=days_ago)

            job = Job(
                company_id=company_id,
                industry_id=ind_id,
                title=jd["title"],
                slug=job_slug,
                description=jd["description"],
                requirements=jd["requirements"],
                benefits=jd["benefits"],
                location=jd["location"],
                remote=jd["remote"],
                job_type=jd["job_type"],
                salary_min=jd["salary_min"],
                salary_max=jd["salary_max"],
                skills_required=jd["skills"],
                is_featured=jd.get("is_featured", False),
                is_active=True,
                expires_at=datetime.utcnow() + timedelta(days=60),
            )
            # Override created_at after construction (server_default is skipped on explicit set)
            db.add(job)
            await db.flush()
            job.created_at = created   # type: ignore[assignment]

            inserted += 1
            category_counts[ind_slug] = category_counts.get(ind_slug, 0) + 1

            if inserted % 20 == 0:
                await db.flush()
                print(f"    💾  Flushed {inserted} jobs so far…")

        await db.commit()

    print(f"\n✅  Done — Inserted: {inserted}  |  Skipped (duplicates): {skipped}")
    print("\n📊  Inserted by category:")
    for cat, count in sorted(category_counts.items()):
        print(f"    {cat:<16} {count}")


if __name__ == "__main__":
    asyncio.run(run())
